main: me.iatog.characterdialogue.CharacterDialoguePlugin
version: 0.5-DEV-BUILD-17.9.21
name: CharacterDialogue
author: iAtog
depend: [Citizens]
softdepend: [PlaceHolderAPI, HolographicDisplays]

commands: