main: me.iatog.characterdialogue.CharacterDialoguePlugin
version: 0.8
name: CharacterDialogue
author: iAtog
depend: [Citizens]
softdepend: [PlaceHolderAPI, HolographicDisplays]
api-version: 1.16

commands: